window.COMMITS = [
"PAG-1105 - Correct the db-migrations job facts in jdk21-migrate-service",
"fix(seeder): route subscription-type writes via /sdk/subscriptions so prelive works (#581)",
"PAG-1105 - Review fixes: drop the stale claim that the pago hook hardcodes origin/master",
"PAG-1105 - Skills, references and release-buddy: JDK 21 is the default lane",
"PAG-1105 - Deploy-kit config: JDK 21 becomes the default lane",
"Add Orange client code fixtures (#580)",
"App Store submission skill: fold in the 4.15.0 learnings (1.3.0) (#579)",
"feat(ab-test): one shared assignment function and trigger, never one per experiment",
"feat(puddy): deterministic migration lock and timeout checks at PR review",
"feat(migration-generator): emit lock timeouts, function owner, and lock-sensitive DDL warning",
"mcp-registry: bump pago-seeder 1.2.0 (new analytics read tools), pago-sdk-seeder 1.0.6 (shared client change)",
"docs(deploy): the guard hook now covers the JDK 21 lane",
"fix(puddy): fit the description to each slot's own cap, not to one number",
"fix(puddy): a long PR description must not take down the panel",
"pago-app-seeder: add analytics read tools (events list + last event date)",
"docs(deploy): state the one override that happened, not a pattern",
"fix(puddy-synthesize): carry what each model SAID, not just where and how bad",
"fix(deploy): an env branch is never a merge source, on either lane",
"fix(puddy): try every configured refuter, not just the first",
"feat(puddy): tell the reviewers what the PR says it is doing",
"feat(deploy): JDK21 lane deploys the work branch, and env config is loaded not retyped",
"fix(agentic-clis): force Python UTF-8 mode so reviewer output stops vanishing on Windows",
"fix(agentic-clis): pin the bin/ reviewer wrappers to LF so Windows pulls stop re-breaking them",
"fix(puddy): recover a slot that answers just after its timeout",
"refactor(backend): make the two staged files disjoint — security said once",
"feat(backend): give backend PRs a security checklist instead of a pentest brief",
"feat(backend): rewrite the backend review rules against the actual monorepo",
"revert(backend): take the rewritten review rules off master pending human review",
"docs(puddy): drop the comment that still argued for per-slot lenses",
"fix(puddy): derive the orchestrator's platform list from the runner",
"fix(backend): correct the review rules against codex's audit — v2.0.0 was wrong",
"docs(puddy): correct the stale web-security comment — the checklist now exists",
"feat(backend): rewrite the review rules against the actual monorepo — 110 to 142 lines",
"docs(readme): list the four agents added for web and backend PR review",
"feat(web): a security checklist grounded in what these repos actually contain",
"feat(puddy): review web and backend repos, with their own rules and nothing borrowed",
"feat(puddy-synthesize): a failed slot no longer penalises a corroborated finding",
"test(bugbench): a defect findable ONLY from a staged caller — and it works",
"fix(puddy-orchestrate): the slot budget was a constant while phase 1's scaled",
"fix(puddy-run-slot): tell the reviewers what _callers is for",
"feat(puddy): a git worktree per review, and two nets that guarantee it goes away",
"feat(puddy-setup): stage the files that CALL what this PR changed",
"fix(puddy-synthesize): MUST-FIX at 0.60, so two of three models can block",
"test(bugbench): plant a REMOVED authorization check — the class the corpus could not hold",
"feat(puddy): record what each slot was actually handed",
"feat(puddy): security via the platform's own checklist, plus codex's review of the prompt",
"feat(puddy): actually pass the slot config — model and reasoning effort",
"fix(jdk21-migrate-service): put HEAD on the work branch in pre-flight, not at commit time",
"feat(puddy)!: drop per-slot lenses — they broke corroboration and did not shape findings",
"fix(puddy-run-slot): widen the lenses — an axis owned by one slot usually goes unreviewed",
"feat(puddy): collect each model's own confidence, separate from the panel's agreement",
"fix(kimi-task): the retry budget was too short, not the wrong idea",
"agy-task: kill the merge-dup string MODELOPT that broke every default run",
"feat(puddy): human PR notes reach the reviewers, not only the poster",
"fix(puddy-run-slot): the staged rules were computed after the prompt was rendered",
"fix(puddy): stage the review rules in scratch (1/7 -> 7/7); retry kimi's 403",
"fix(puddy-run-slot): \"NO FINDINGS.\" was scored as a dead slot; gemini needs real paths",
"fix(puddy-orchestrate): normalise reversed line ranges",
"fix(puddy-orchestrate): --detach wrote the verdict where phase 2 does not look",
"fix(puddy): \"run it in the foreground\" was impossible to obey — detach + bounded await",
"fix(puddy)!: the agent backgrounded the orchestration and exited",
"feat(puddy)!: the spec stops being the program — 1081 lines to 203",
"test(puddy): matched-panel comparison on a real PR; agent path broke its own table",
"fix(puddy-orchestrate): read setup's manifest instead of inventing its interface",
"feat(jdk21-migrate-service)!: act on the pago-pos-user run feedback",
"feat(puddy-orchestrate): the panel loop as a program, and a quorum bug it found",
"fix(gemini): the slot could not read the diff, and exited 0 saying so",
"feat(puddy-run-slot): rounds 2/3/refute, and claude as an ordinary slot",
"chore: remove the softfactory-deploy skill — the environment is gone",
"feat(puddy): phase 6 as a program, with a gate that explains rather than matches",
"refactor(jdk21-migrate-service)!: the skill no longer connects to any database",
"fix(jdk21-migrate-service): bound the readiness sweep — scope, budget, psql timeout",
"fix(pago-deploy-kit): two JDK 8 regressions, and the config the skills never sourced",
"fix(puddy): make cluster splitting reimplementable; accept both schemas defensively",
"fix(puddy): two contradictions in phase 6 that changed verdicts silently",
"feat: claude as refuter fallback; gemini-task replaces agy-task",
"fix(pago-deploy-kit): map the -v1-1 services in the capacity check too",
"refactor(pago-deploy-kit): fleet and lane data into config/, not skill text",
"fix(agentic-clis): agy auth probe checked a directory, not the token",
"perf(puddy): stop cross-challenging findings a challenge has never rescued",
"fix: unanchor the sentinel everywhere it is parsed, not just in puddy",
"fix(bugbench): a line-anchored sentinel dropped grok's CRITICAL finding",
"feat(bugbench): deterministic recall harness — and a slot that failed auth scored as clean",
"feat(agentic-clis): puddy-verdict — read a puddy verdict once, not six times",
"perf(puddy): do setup in one process instead of ~15 orchestrator turns",
"feat(puddy): honour sufficient_quorum when the count falls below min_healthy",
"fix(pago-deploy-kit): review findings — quoted-tilde abort, and guards moved into bash",
"Add pr-triage skill — risk-rank PR files, mark the noise as Viewed (#532)",
"skill(deploy-to-environment): v2.0.0 — JDK 21 lane, on one shared deploy kit",
"Updated rework analysis learnings",
"skill(deploy-to-environment): v1.3.1 — verify the swarm service name, correct exit codes",
"skill(jdk21-migrate-service): v1.0.0 — per-service JDK21/Boot3 migration checklist",
"reclaim-disk: add README, worked example, and evals (v1.0.1)",
"agy/grok-task: guard empty-array expansion under set -u (bash 3.2 crash)",
"Add shared/reclaim-disk skill + command",
"Cut PR-review fleet cost: deterministic slot runner + dollar instrumentation",
"feat(tag-release) 1.0.0 — tag a merge commit and push, with branch + tag confirmed",
"Propagate the #538 hardening to the sibling figma-screens skills (#540)",
"Harden figma build/audit skill against silent quality loss (#538)",
"feat(intake-orchestrator) 3.8.0 — decision briefs: every choice pickable in five seconds",
"fix(puddy): repair the synthesis arithmetic — verified against 80 stored runs",
"fix(kimi): handle the quota failure the incident actually produced, and unbreak the large-diff fallback",
"fix(pr-review): make the refuter speak grok's own language, and stop the fallback bypass",
"fix(pr-review): fail the verified field closed, and stop contradicting the banner rule",
"fix(pr-review): pin the panel's models and effort, and close the stale contradictions",
"agy-task: default to latest Gemini Flash family, effort-mapped",
"fix(pr-review): keep reviewer scratch out of target checkouts",
"fix(pr-review): self-healing probes, honest failure detection, and a real refuter",
"feat(ios-coder): add localization + shared-scheme non-negotiables; 1.0.1 -> 1.0.2",
"feat(intake-orchestrator) 3.6.0 round 2 — deep links land ON the passage + kimi review fixes",
"fix(okr-update): address multi-model review; add macOS lane, harden write path",
"fix(answer-prd-questions): harden pin script and close review findings",
"fix(intake): layer-2 help leads with the PATH case, not reinstall",
"fix(intake): sanitize the probe protocol, correct the layer-2 rationale",
"fix(intake): find judge CLIs off PATH, name the missing layer",
"feat(intake-orchestrator) 3.6.0 — question doc-links: clickable references + console context",
"fix(pago): make the ws picker and installer work on Windows cmd/PowerShell",
"skill(dark-mode): v2.15.0 — Phases K and L, a triage agent, and the lessons the JSON never sees (#527)",
"skill(restart-service): v1.2.0 — reaction-only Step 6, report real task node",
"fix(health): kimi model id is kimi-code/k3, not kimi-k3 (#524)",
"PAG-856 — [session 2026-08-18] seeder address fix + ios driver breaker corrections (#520)",
"health: add Claude as a real fifth slot",
"Wire the PR-review model slots to transports that actually work",
"feat(skills): add migration-check review skill",
"PAG-981 - test(pago ws): assert the guarantee, not the POSIX mechanism",
"PAG-981 - feat(pago ws): wire every .claude kind a repo ships, not just three",
"perf(agents): trim 10 more agent descriptions (~310 tokens per turn)",
"PAG-932 - docs(pago): a walkthrough for someone installing this for the first time",
"PAG-932 - perf(pago): read the registry once, not once per lookup",
"PAG-932 - perf(pago): stop paying for eleven subprocesses on every invocation",
"PAG-932 - fix(pago install): jq on Windows silently translated every path it wrote",
"PAG-932 - fix(pago env): a junction is not a symlink, and the guard trusted `[ -L ]`",
"PAG-932 - fix(pago): what a real Windows runner found",
"PAG-932 - fix(ci): the Windows pre-checkout step inherited a directory that did not exist yet",
"PAG-932 - test(pago): actually run Windows in CI instead of assuming it",
"PAG-932 - feat(pago): Windows support, built on the assumption of no symlink privilege",
"PAG-931 - feat(pago): Linux support, and the CI that proves it",
"PAG-930 - fix(pago ws): arrow keys crashed the picker on stock macOS bash",
"PAG-930 - refactor(pago ws): drop fzf, the picker is pure bash now",
"PAG-928 - perf(pago install): read the config once, not nine times",
"PAG-928 - fix(pago env): the adopt prompt names what you are actually deciding",
"PAG-928 - fix(pago env): unique scratch path, and clean it up on every failure",
"PAG-928 - feat(pago env): one master per credential file, symlinked into workspaces",
"perf(agents): trim 20 agent descriptions to cut ~4.75k tokens per turn",
"fix(pago install): a second run must not edit what you typed",
"fix(pago): stop assuming ~/_repos — ask, derive, and keep it in config.json",
"fix(pago install): write to the rc file the login shell actually reads",
"feat(pago install): a setup wizard, and ~/.claude is no longer pago's business",
"test(pago ws): 71 contract tests — and the config bug they immediately found",
"feat(pago ws): remember the last five presets, drop the dead state keys",
"feat(pago ws): user-defined presets and repos in ~/.pago",
"feat(pago): per-developer config at ~/.pago/config.json, and a branch toggle",
"fix(pago ws): scope pago-loto-connect to the pago full-stack family",
"feat(pago ws): pull the web surfaces into the full-stack presets",
"fix(pago ws): freshen the branch a checkout is actually on",
"fix(pago ws): freshen shared checkouts — presence is not currency",
"refactor(pago): fold the workspace tool into a `pago` CLI with namespaces",
"fix(create-workspace): fail loudly instead of building a hollow workspace",
"feat(create-workspace): multi-repo workspace tool",
"feat(pago-seeder): pago_set_loto_ip_whitelist — toggle the loto IP-location bypass (#510)",
"Address PR review: fix Phase 4 emulator ref + restore /data disk check",
"feat(sync-claude): auto-wire per-platform rules hook (rules/*.md + add-once CLAUDE.md line)",
"feat(intake-orchestrator) 3.5.0 — guided entry: no-attachment starts become an interview (#508)",
"feat(intake-orchestrator) 3.4.0 — human-friendly runs: the PR-96 seven (#505)",
"fix(pr-review-notify): report terminal CI failure to the watcher (#507)",
"experimental: intake orchestration benchmark — self-authored codex-sol + kimi-k3 variants (#504)",
"ios-inspector-gadget: self-heal the fresh-sim first-boot XCUITest AX failure",
"PAG-791 — [session 2026-08-06] make a stale gadget build fail loudly instead of serving old code (#499)",
"feat/PAG-791-gadget-lab-emulator-ram-is-too-small (#492)",
"Add Linear MCP automation to iOS and Android workflows (#498)",
"Fix session-transcript path derivation in create-pr Step 4.5.2",
"Support explicit ZHTML project uploads (#494)",
"Use PAGO_ZHTML_TOKEN for Report Hub",
"Untrack the xcodegen-generated ios-ax-driver.xcodeproj",
"De-dupe the premortem skill — keep shared/, drop the backend/ copy",
"feat(ab-test-orchestrator): add Web platform + mobile transport mode, kill-switch Phase-0 question (#440)",
"skill(dark-mode): v2.14.0 — the screen-side Mode sweep, and a rule that was only half true (#477)",
"android-release-notes: render the final file through /beautify (v1.2.0) (#481)",
"kotlin-style: document the ktlint-gated formatting rules",
"Add figma-redesign-impact-audit skill (#487)",
"report-hub: resolve PAGO_PAT from ~/.pago-qa too, not just the environment (v1.1.0)",
"Self-heal a pip-less venv in sync-venv.sh, and stamp the venv's own Python",
"Fix the two Linear-lane bugs the HYP-170 run exposed",
"20260803 - update skill catalog",
"Pin mcp<2 — 2.0.0 removed mcp.server.fastmcp and broke every fresh seeder venv",
"Version all 4 MCP servers and block stale builds at the tool-call boundary",
"20260731 - update backend skills and agents",
"Teach the QA chain to read and move Linear tickets, not just Jira",
"Teach the sibling QA skills about the qa-ticket-prep-figma artifacts (additive only)",
"Embed the design frame beside the screenshot on failing rows (report v1.2.0, skill v2.2.0)",
"qa-ticket-prep-figma: persist the Figma extraction verbatim so the tester can read it (v2.1.0)",
"qa-ticket-prep-figma: require a design — ask for the link or stop (v2.0.0)",
"qa-ticket-prep-figma: gate Figma extraction on relevance, warn when there's no design (v1.1.0)",
"qa-ticket-prep-figma: Figma-driven QA prep, HTML results report instead of TestRail (v1.0.0)",
"fix(okr-update): address multi-model review board findings; v0.1.0 -> 1.0.0",
"feat(okr-update): add Pago OKR read/update skill",
"Revert \"Merge pull request #459 from PagoApp/feature/qa-ticket-prep-figma-source-of-truth\"",
"skill(dark-mode): v2.12.0 — the brand-plate conflict, and the sweep bug that hid it (#476)",
"defer ENV_LABEL/BRANCH tag fix to #473, keep only the UNKNOWN-row fix it misses",
"fix(report-hub): a scope 403 can be a ROLE, and then a new token cannot help",
"fix(deploy-to-environment): expected deploy tag uses ENV_LABEL, not BRANCH",
"factory-tools: scope backend maven verifiers to impacted modules",
"Close every LINK route to the verdict, and the edges each earlier guard missed",
"skill(dark-mode): v2.11.0 — Phase I maps PAIRS, not leaves, with a runnable sweep gate (#470)",
"Close 24 defects codex + kimi found in the previous commit's own fixes",
"Gap the answer stage's input boundary — a missing panel is not \"nothing to ask\"",
"feat(qa): gadget-discovery + gadget-implementation — the two missing lifecycle modes",
"feat(report-hub): publish.sh classifies the failure, so VPN and token never get swapped",
"fix(gadget-lab): teardown removes both halves of an AVD, create reclaims orphans",
"Harden the gate's output stage against untrusted packs and unrecorded skips",
"factory-tools: fix inert DAG gating + repair semantic merge damage",
"gate report: bounce summary, rule legend, ranked topics + an interactive answer stage before a bounce",
"Classify a timed-out partial that only announces its next step",
"feat(intake-orchestrator): the report explains its own verdict + \"Ask a colleague\" multiplayer Q&A",
"floorman: hand the orchestrator to a CLI lane at 88% of the Claude 5h window (Q12)",
"floorman: a stuck milestone barrier no longer idles the whole factory + halve the unit_test double-run",
"gate: plain-language voice + parallel P4 reviewer panel",
"agentic-clis: close the exit-code truth chain + 30d audit fixes",
"factory-tools/gate-tools: CRLF-safe jq on Windows",
"pm-tools: speak UTF-8 regardless of locale (fixes 2 pm-tests failures)",
"android-qa-ticket-prep: read the ticket's Figma link as a UI source of truth (v1.1.0)",
"docs(qa): resolve pago-testing through the repo registry, not the sibling layout (#no-issue/infra) (#458)",
"pm-eng-planner: intake-grade report publishing",
"sync-claude: register pago-sdk-seeder with --mcp (#no-issue/infra) (#455)",
"fix(gadget-lab): strip CRLF from adb devices output in serial_for_avd (Windows)",
"floorman: give each iOS device zone its own simulator + apply the operator effort matrix",
"[no-issue/infra] ios-inspector-gadget: deterministic taps + deploy drift guards (#398)",
"fix(android-inspector-gadget): add inter-tap delay to input_pin (v1.3.1) (#372)",
"gadget-script-runner v2: the mini-testers run + supervise + report on scripted missions (#454)",
"retire the sdk-gadgets/ references — the SDK corpus is YAML now, not this agent's (#453)",
"gadget: in-house multi-window a11y capture — see dropdowns, dialogs, toasts (#450)",
"gadget-lab: device lifecycle as scripts the agents run, not prose they retype (#449)",
"feat(pago-seeder): leaked-identity cleanup + leak ledger, custom-password login (#451)",
"gate/intake: drop the run reports, enforce W2 in the schemas instead",
"gate report: real pm-eng handoff prompt + working copy button",
"gate: move status report under docs/, drop the machine-local pack path",
"gate: document the W2 stage-completeness blocker + euplatesc pack status",
"factory-orchestrator: v05 — the insurance/pad run's lessons, adversarially reviewed",
"factory-orchestrator: addendum 49 — refine NE118, naming the delivery ACTION flipped the outcome",
"pago-app-seeder: complete PAD address fixtures (S0) + offers diagnose tool (S1)",
"factory-orchestrator: addendum 47 — NE139, ui_validate cannot see occlusion or transition pacing",
"added backend and infrastructure structure",
"factory-orchestrator: withdraw NE136; file NE138 — transcript snapshots are not current state",
"factory-orchestrator: addendum 46 — NE135 observer blind spot, NE118 confirmed in a third orchestrator",
"factory-orchestrator: addendum 45 — NE134, the delivered PR decays at the human gate unwatched",
"factory-orchestrator: addendum 44 — cross-run lessons from the Loto auto-payments run",
"factory-suggestions: fix addendum-43 item numbering (NE132/NE133 were 144/145, now 145/146)",
"factory-suggestions: addendum 43 — the X that went nowhere; NE102 recurs a third time (NE132-133)",
"intake↔gate: pack alignment contract + Windows encoding/EOL fixes",
"factory-suggestions: addendum 42 — the PR-side reviewer is a gate the local loop never consults (NE131)",
"factory-suggestions: addendum 41 — re-verification passes; NE118 reaches its terminal form",
"factory-suggestions: addendum 40 — human eyes find 5 bugs, adversarial review finds 2 more (NE129-130)",
"factory-suggestions: addendum 39 — demo path works; credential debt is compounding (NE128)",
"factory-suggestions: addendum 37 — punch-list wave runs outside the factory; NE118 confirmed twice (NE123)",
"create-pr: enforce Linear ticket create + PR link (android + ios)",
"factory-suggestions: addendum 36 FINAL — run-004 closes 59/59 SUCCESS; the walls were data fixtures (NE122)",
"factory-suggestions: addendum 35 — API-seeding busts all 3 \"unfixable\" walls, 56/59 -> 58/59 (NE119-121)",
"factory-suggestions: addendum 34 — operator reopens the blockers; seed fixtures via the app's API (NE118)",
"factory-suggestions: addendum 33 — run-004 CLOSED at 56/59 + closing scorecard (NE116-117)",
"factory-suggestions: addendum 31 — list a3 walled, ceiling lifted to 56/59 (NE107-110)",
"factory-suggestions: addendum 30 — deadlock released; operator confirms the NE105 fix; ceiling 51/59",
"factory-suggestions: addendum 29 — a signature collision deadlocks an unrelated lane (NE105-106)",
"factory-suggestions: addendum 28 — 2 items close, cap->60h (operator), NE93 misdiagnosed (NE103-104)",
"factory-suggestions: addendum 27 — details closes clean + the phantom-coverage footgun (NE102)",
"factory-suggestions: addendum 26 — milestone flush fires + thrashes on its own spike (NE99-101)",
"factory-suggestions: addendum 25 — device lane real verdicts + the NE94 root cause (NE96-98)",
"factory-suggestions: addendum 24 — renew finalization + first-launch device wall (NE93-95)",
"suggestions: addendum 23 — device provenance proven, credential fragility, effort-pin",
"suggestions: addendum 22 — sim reaper, device-MCP SPOF, tools-path re-resolve, value-shape schema",
"suggestions: addendum 21 — publish HALT mislabel, run-dir clobber, orphaned watcher on teardown",
"suggestions: addendum 19 — no-eval-of-worker-state (RCE), fail-closed crypto, same-UID limit",
"factory-orchestrator: harden milestone barrier per second external review (grok/codex R2)",
"suggestions: addendum 18 — red-team the gate itself, meta-worker watchdogs, presence vs progress signals",
"factory-orchestrator: harden proof cache + watcher per external review (grok/codex R1)",
"suggestions: addendum 17 — verify-cache threat model, permanent-dirty-file input, peer handshake",
"factory-orchestrator: read-only review/security zones drop the build lease",
"factory-orchestrator: milestone-batched build proofs + memoization cache in mark-done.sh",
"suggestions: addendum 16 — PR #441 status, worker mandate-drift gate",
"factory-orchestrator: add watch-zone.sh completion watcher (anti-stall)",
"suggestions: addendum 14 — publish-report chain fix, cap-change verb confirmed, 4th re-verification catch",
"suggestions: addendum 13 — publish HALT recurrence (tailnet-down root cause), operator-cap-change verb",
"suggestions: addendum 12 — atomic evidence handoff (idle-while-incomplete class)",
"suggestions: addendum 11 — per-run env freezing, recompile discard consent, attempt-free manual stops",
"fix(factory-tools): verified no-op path for implement zones (re-verification runs) (#439)",
"suggestions: addendum 9 — run-002 recurrence confirmations, step latency, notification lag",
"Move grill-me command into pago-shared-config",
"suggestions: addendum 7 — enter_pin tool bug, disposable payment accounts, exact-operation health probes",
"android-intercept: add Windows/Git Bash field notes + generic spawn driver",
"suggestions: addendum 5 — spawn-time effort, live worker retune, cross-env validation, hermetic tests",
"feat(factory): ui_validate workers on sonnet/high (mini-tester speed)",
"feat(backend): release-buddy — CLEAN heartbeats + early crash-loop rollback (1.5.0)",
"suggestions: addendum — verify-gate regression suite, tool-fault attempts, per-bead ledger",
"fix(factory-tools): unquote C-quoted paths in mark-done diff-manifest check",
"factory-orchestrator: 31 improvement suggestions from insurance/pad run monitoring",
"docs(backend): release-buddy — prod Swarmpit token var spelling fixed upstream (1.4.1)",
"fix(backend): release-buddy — defects found in first live run on PR #4988 (1.4.0)",
"feat(backend): release-buddy — confirm the watch set with the developer (1.3.0)",
"feat(backend): release-buddy — fixed per-step output templates + HTML export (1.2.0)",
"feat(backend): release-buddy — temp-dir state + prod Prometheus watch (1.1.0)",
"feat(backend): add release-buddy watchdog agent",
"caveman: default session intensity to ultra",
"feat(factory): promote home-insurance run steering into ios team file",
"fix(factory-tools): Swift Testing parser fallback + 'design' lane in lanes-witness schema",
"ios-mini-tester: mandatory DoctorQlaw QA-nav preflight gate (Check 7) (#428)",
"gadget-cases-and-missions: add anti-patterns for bug-IDs, coverage-state & platform HOW (#427)",
"sync-claude.sh: usable non-interactive + live picker + MCP management (#426)",
"feat(sync): one canonical sync-claude.sh (symlink + prune + manifest); retire competing mechanisms (#425)",
"fix(pm-eng): default planner runDir to <initiative>/implementation on the bead branch",
"Harden milestone-ship per review: null-safe jq, add-A tolerance, --reason flag",
"Milestone-ship: every finished milestone ships per lane + /backend-ship command",
"Device labs + conditions + gadget-lab skill for mini-testers (#422)",
"Backend review role: cli-only (family split vs Claude implementer)",
"fix(caveman): stop self-setup hook from duplicating every session (#415)",
"docs(inspector-gadget): how to update/install the MCP to get latest (incl. rebuild) (#421)",
"HYP-171 - feat(android): bundle the link_pr toolkit with the skill",
"mini-testers: gadget Cases & Missions parity (android 2.0.0) + drop learnings (ios 3.0.0) (#420)",
"HYP-171 - feat(android): add android-linear-link-pr skill",
"SDK QA headless support: inspector-gadget 2.2.0 (bundle_id), mini-tester 2.1.0, pago-sdk-seeder (#418)",
"pm-eng: v3 runtime — reference Workflow + timing + machine degraded-gate + batch emit + stamp — v3.4.0",
"iOS submission skill: add rejection-response playbook (v1.2.0) (#401)",
"feat(pago-backend-log-download): disable SSH host-key verification for swarm fetches (skill v1.1.0)",
"docs(android-intercept): add Windows + real-world learnings (v1.2.0)",
"feat(android-ship): anchor the run with the /goal skill in Phase 1",
"fix(pago-backend-log-download): breaking PAGO_SSH_USER gate + accurate PARTIAL missing-node source (v1.0.1)",
"Add pago-backend-log-download skill + agent",
"Remove PM report hero stats",
"fix(figma-deep-dive): §6.6 checker exempts a node that IS an instance",
"feat(figma-deep-dive): enforce authored-node DS binding + CTA/auto-layout rules",
"chore(android-commands): add android-handoff + genericize android-ship (rebased on master) (#383)",
"fix(pago-report-hub): move skill to pago/skills, correct size cap to 1MB (#407)",
"Add pago-report-hub skill (previously local-only under ~/.claude) (#406)",
"Refine /android-ship: leaner prose + more skill hooks (#404)",
"intake: make generated reports more useful (R1–R6)",
"fix(beautify): make hero-meta card split independent of blank-line formatting",
"Add /pago-fetch-workspace command: idempotent Pago workspace bootstrap",
"feat(sdk-assets-parity): add --github remote fetch + --integrator scoping",
"Add milestone-level Linear projection + live factory progress report",
"fix(beautify): port tabs/progress-ring/verdict-card/hero-meta into report template",
"fix(pm-progress-report-schedule): fix all CRITICAL/HIGH/MEDIUM-HIGH round-3 findings",
"fix(pm-progress-report-schedule): fix remaining HIGH/MEDIUM-HIGH round-2 findings",
"fix(pm-progress-report-schedule): fix regressions and Windows bugs from round-2 review",
"fix(pm-progress-report-schedule): address critical/high findings from multi-model review",
"chore(pm-progress-report): add missing version fields",
"fix(pm-progress-report-schedule): wire the Linear-only MCP isolation into the skill",
"fix(beautify): add self-verification for the radio-tab structural bug",
"fix(pm-progress-report-schedule): keep newest run at top of the log file",
"fix(pm-progress-report): emit header meta facts for beautify's hero row",
"fix(pm-progress-report-schedule): install local scheduled job instead of cloud routine",
"fix(beautify): document card-style hero meta row and fix verdict-card gradient cutoff",
"feat(product): add pm-progress-report-schedule skill for daily automation",
"premortem: rename skill from what-can-go-wrong → premortem",
"Fail bundle build on missing sentinel",
"Retire legacy backend Linear skill",
"what-can-go-wrong: add hot-path DB-read + hedge-word anchor to Phase 5 / FM-K",
"docs(agentic-clis): correct plugin install steps in install.sh header (#394)",
"fix(agentic-clis): recognize ~/.kimi-code config in kimi auth probe (#393)",
"intake-tools: fix 4 determinism-core bugs found in a live run",
"chore(pago): remove legacy Linear ticket skills",
"fix(pago): require English Linear tickets",
"fix(pago): prefer impacted integrator in Linear tickets",
"20260714 - move skills and agent to shared config",
"Harden android + backend floorman teams to Loto-auto-proven level",
"feat(pago): unify Linear ticket creator skills",
"intake tooling: PRD-implied missing states = resolve-or-ask, not hard-block",
"20260710 - fix deploy to env slack post",
"feat(ios-mini-tester): own Cases & Missions mode end-to-end (v1.1.0)",
"feat(intake): st2 Design handover adopts the approved template page (SKILL 2.29.0, publisher 1.5.0)",
"fix(intake): +x mode on archive-stage-runs.sh + human-wait.sh (invoked by path — 644 fails on macOS)",
"feat(agents): judge/review CLIs go through the agentic *-task wrappers; MSYS-safe agentic-probe",
"fix(design-studio): plugin.json author must be an object (v1.2.1) (#381)",
"fix(dark-mode-generator): plugin.json author must be an object (v1.0.2) (#380)",
"feat(dark-mode-generator): marketplace plugin + house-style README (#379)",
"feat(figma-deep-dive): self-installing plugin + /figma-setup doctor (v0.12.0) (#378)",
"feat(Design/skills): figma-dark-mode-generator skill (#365)",
"Address #376 review: add R-review-8 (domain->ui), fix figma render path, neutralize examples",
"Abstract the intake improvements — drop feature-specific examples",
"Intake tooling: distill Freemium Paywall v2 retro into stage improvements",
"pago-count-mobile-releases: missing token is not a failure",
"pago-count-mobile-releases: input-agnostic, drop Keychain/personal refs",
"pago-count-mobile-releases: de-personalize — generic token resolution",
"pago-count-mobile-releases: add Slack connection preflight",
"Add pago-count-mobile-releases skill",
"gate: verdict-gated PM/ENG next-step recommendation (report + console)",
"gate report: areas vocab + per-phase timing + resume + row layout + expandable plain-English concerns",
"perf(intake): deterministic st2 render + spawn-batched status page — publisher ~10x faster",
"gate: widen dimension-score `passes` cap 3->4 for the 4-family panel",
"gate: drop FAMILY-level judge!=builder; keep instance/run-id self-grade",
"feat(adb-input-helper): build the missing TG01 helper IME APK (v1.3.1)",
"feat(intake): per-judge scores + failure details on judge rows; fix run-elapsed calculation",
"feat(intake): status heartbeat + structural sub-step events — the page updates without model discipline",
"feat(intake): expandable Run-preflight card — start/duration, environment details, full checks",
"feat(intake): guardrail 8 — every stage publishes, machine-checked, never skippable",
"video-split: convert to mp4 in the same pass as the split",
"feat(intake): visual st2 Design handover — embedded screen/state images, fit-to-1MB, click-to-enlarge",
"Remove unused codex/skills/android-mini-tester",
"feat(intake): live sub-step progress — page updates on every subagent/judge transition",
"Use \"Loto\" (single t) for the Loto product token",
"Skip proceed-gate by default and require reading the full Slack thread",
"feat(intake): intake-publisher agent — parallel report/HTML publishing at a mandatory PUBLISH step",
"Move gadget-mobile-report into pago/skills",
"Add bracket exceptions, integrator inference, and update-existing-issue guidance to frontend ticket creator",
"Make /pago-report-hub publish mandatory, not fallback-on-first-failure",
"Add gadget-mobile-report skill: HTML testing reports with screenshot proof",
"intake: Voice contract — human language + Q→A impact on every user touch",
"intake: FIX (bug) lane — multi-input lanes on the 10-stage spine",
"docs(figma-deep-dive): rewrite family guide as figma-screens-README.md, add install steps",
"fix(android): skip malformed JSON in sdk-assets live parity gate",
"Address PR review feedback",
"Floorman wave-2 obvious: functional proof gates review + steering ledger + QA playbook",
"feat(android-inspector-gadget): add occurrence param to tap_ax_id/tap_label",
"Remove unused /android-run-android-emulator, mirror iOS delegation fix",
"Fold /ios-run-simulator into ios-mini-tester; make sim teardown mandatory",
"Remove unused codex/skills/ios-mini-tester",
"docs(figma-deep-dive): add FIGMA-SCREENS.md family user guide (0.13.1)",
"Fix DerivedData leak in ios-ax-driver, rename sim naming to gadget-lab-*",
"fix(figma-deep-dive): propagate checklist parity into execution docs + de-stale personal-skill references",
"chore(figma-deep-dive): bump to 0.13.0, register the figma-screens-from-* family",
"refactor(figma-deep-dive): remove old product/skills location of the video skill",
"feat(figma-deep-dive): migrate figma-screens-from-video into the plugin (slimmed to adapter form)",
"refactor(figma-deep-dive): slim claude-design skill to adapter form (0.2.0)",
"feat(figma-deep-dive): add legacy source-adapter briefs",
"feat(figma-deep-dive): add figma-screens-from-legacy skill (existing-Figma conversion)",
"feat(figma-deep-dive): extract guarded-build core (Phases 2-7) into build/",
"Add implementation plan for figma-screens family refactor",
"Add design spec: figma-screens family refactor",
"fix(figma-deep-dive): null-guard getNodeByIdAsync in audit-fix recipes",
"fix(figma-deep-dive): parity carve-out in adapter briefs + review polish",
"chore(figma-deep-dive): bump to 0.11.0, register figma-screens-from-claude-design",
"feat(figma-deep-dive): add Claude-Design source-adapter briefs",
"feat(figma-deep-dive): add figma-screens-from-claude-design skill",
"feat(figma-deep-dive): move shared build references into plugin (build/)",
"Add implementation plan for figma-screens-from-claude-design",
"Add design spec: figma-screens-from-claude-design",
"fix(android-inspector-gadget): validate required string args before use",
"feat(backend/skills): add linear-support-task skill",
"fix(intake-preflight): plain-language CLI helper messages",
"Drop static tool index from pago-seeder-guide, discover tools live instead",
"Add pago-seeder-guide skill: route to the right pago-seeder tool",
"Update gadget-cases-and-missions path refs to pago-gadgets/ (#353)",
"Add cases-and-missions shared QA skill (#352)",
"fix(ios-asc-skill): make setNative work for both textarea and input elements",
"feat(ios): add ios-agent-creator skill",
"docs(ios-asc-skill): harden App Store submission skill from live-run learnings",
"feat(figma-screens-from-video): wire Phase 6 audit + Phase 7 fix + builder stamps; v1.3.0 -> 1.4.0",
"feat(figma-screens-from-video): audit-fix.md — Phase 6 audit + Phase 7 fix recipes (re-baselined)",
"spike(figma-audit): record feasibility verdicts (key harvest, identity, defensive swap, screenshot verify)",
"fix(beautify): guard against uninvited hidden content and invented dark mode",
"fix(figma-re-baseline): recipe prop-order + audit-doc supersession markers + naming-fix locus (review fixes)",
"docs(figma-audit-fix-loop): re-baseline design spec + plan to merged convention",
"fix(figma-screens-from-video): re-baseline to merged per-screen-master model; v1.2.0 -> 1.3.0",
"feat(figma-deep-dive): init renders conventions card to native Figma styling",
"[qa] Consolidate to a single iOS-Simulator MCP (ios-inspector-gadget) + reliability (#346)",
"Add android-sdk-dependency-audit skill",
"fix(figma-deep-dive): CRLF-safe markers + line-ending normalization in render-screens-section",
"feat(figma-deep-dive): master/variant delta-only screen naming convention",
"release-notes-qa: drop the standalone agent",
"20260706 - move skills, agents and commands to share config",
"[qa] pago-app-seeder: launch-env, user-extra flags & flow-picker tools for QA bypass (#335)",
"release-notes-qa: move execution to a deterministic Workflow script + add a standalone agent",
"Fix iOS team build verifier: add generic simulator destination",
"Add machine-readable flow channel (connectors are FigJam-only)",
"Add figma-screens-from-video skill",
"Fix diff_manifest_check silent pipefail crash on modify-only implement zones",
"Harden factory-orchestrator (Floorman) — 4 v0.1 bugs from first live run + iOS team notes",
"docs(readme): Software Factory plain-language tour + Floorman description",
"feat(answer-prd-questions): new skill — answer PRD Open Questions from code",
"pm-eng: S1-S6 speed upgrade — deterministic fragment assembly + parallel review wave — v3.1.0",
"fix(beautify): missing local image = parity FAIL, never publish a broken <img>",
"feat(beautify,intake): parallel stage reports — st2/st3/st6 render via beautify v2 + Report Hub",
"feat(beautify): v2 — deterministic template engine + benchmarked freeform engine ladder",
"design-studio: tighten grounding integrity (Fable review batch)",
"feat(factory-orchestrator): wave1 batch4 — failure-identity package (opus-implemented, fable-reviewed)",
"security(android): add defensive-controls-2026 reference (blue-team companion)",
"security(ios): add ios-defensive-controls-2026 reference (blue-team companion)",
"feat(factory-orchestrator): wave1 batch2 — evidence provenance package (opus-implemented, fable-reviewed)",
"intake: single-flow scope — figma inventory + research agents stay inside one flow",
"Add release-notes-qa skill — deep-research QA release notes for android-pago",
"fix(factory-orchestrator): gemini review — error-suppress jq lookups on ledger lines",
"intake: Stripe-level status page — stat tiles, stage emojis, Reports label, closing block",
"intake: add CLI_PROGRESS touch — per-CLI liveness during judge/challenger fan-out",
"intake: preflight report shows readiness verdict only, no environment PII",
"what-has-gone-wrong: land top 10 fixes from 9-seat multi-model skill review",
"Consolidate android-ac-to-testrail into pago-qa-skills only",
"figma-screen-inventory: group frames by shared master component (v1.7.0)",
"Add android-create-intro-screen-dashboard skill",
"pm-eng: address codex + agy adversarial review — v3.0.2",
"pm-eng: address Gemini PR review (encoding + malformed-input guards) — v3.0.1",
"intake: resolve PR #323 review findings (Gemini + codex + agy)",
"intake: configurable PRD source file (prd_file, default prd.md)",
"pm-eng: v3.0.0 — task-spec DAG (no agent assignment, no waves)",
"fix(factory-orchestrator): multi-model review round 2 — codex + grok + agy findings",
"Add simulator teardown to sim-creating skills/agents",
"fix(factory-orchestrator): review round — self-review + kimi adversarial findings",
"Remove hardcoded TestRail credential fallback in android-ac-to-testrail",
"feat(factory-orchestrator): slice 4 — skill wrap (SKILL/ONBOARDING/playbooks/references/launcher)",
"pm-eng: ingest real intake packs (adapter + real fixture) — v2.3.0",
"feat(factory-orchestrator): slice 3 — loop core, 73-check conformance harness green",
"updated the figmascreen extractor",
"feat(factory-orchestrator): slice 1+2 — schemas, probes, compile, plumbing",
"Reject CR/LF + code-fence injection in rendered plan fields (check #10)",
"Lock Description section + document the mechanical/semantic trust boundary",
"Close two final gate holes: duplicate .md heading + C6 reachability",
"Wire work-order v2 into the planner + section-equality gate (Commit D)",
"Harden the work-order gate — close the codex cage bypasses",
"Work-order render + validate gate + close the computed_triple bypass",
"Interface registry (D9) + move the AC trust core into the runner-gate",
"Work-order AC trust core: Gherkin C2'/C5/C5b + AC->test binding (C6)",
"fix(pm-progress-report): harden PRD fetch error handling and define score-grid format",
"End-to-end validation + adversarial hardening (Iteration 3)",
"figma-screen-inventory: address CRITICAL and HIGH review findings from #316",
"Figma-flow milestone staging + walking-skeleton bias (Iteration 2)",
"Lean rewrite of PM/ENG Planner agent + card (Iteration 1)",
"agentic-clis: isolate the grok leader socket per invocation (fix 0-byte under concurrent fan-out) (#315)",
"gate-tools: stop --real runs from mutating the intake pack (reviews-real → run dir) (#311)",
"figma-screen-inventory: fix two candidate-extractor bugs found in the v1.5.0 confirm run (v1.5.0 -> v1.5.1)",
"figma-screen-inventory: deterministic candidate extraction (v1.4.0 -> v1.5.0)",
"figma-screen-inventory: JSON-first output — render markdown from the JSON (v1.3.0 -> v1.4.0)",
"figma-screen-inventory: add per-phase run-timing report (v1.2.0 -> v1.3.0)",
"figma-screen-inventory: two-tier state grouping + inferred navigation (v1.0.0 -> v1.2.0)",
"feat(release-notes): customer-facing \"What's New\" in Pago voice (#312)",
"gate-tools: degrade-not-die on reviewer wrapper failure + grok-build seat (#314)",
"agentic-clis: isolate the grok leader socket per invocation (fix 0-byte under concurrent fan-out)",
"fix(pm-progress-report): address critical and high severity review findings",
"inspector-gadget: decouple input from host + fix text-input wedge + agent isolation (#313)",
"Swap PM/ENG detail-UI gate to figma-deep-dive; unify factory/ structure",
"gate-tools: fix bash-3.2 empty-array crash, configurable reviewer timeout, optional grok family (#305)",
"feat(ios-mini-tester): structured preflight checks, seeder dry-run, status file (#309)",
"chore(figma-deep-dive): agent 1.5.0 -> 1.5.1 (linter version bump) + README version-table sync",
"fix(figma-deep-dive): escape agent description YAML (invalid double-quote scalar)",
"fix(figma-deep-dive): strict-YAML-safe frontmatter descriptions",
"docs(figma-deep-dive): README + version reconcile (plugin -> 0.6.0)",
"feat(figma): starter template procedure + finalized scaffold-spec",
"fix(figma): render multi-line bold + reset table state in designer-surfaces generator (review fixes)",
"feat(figma): render designer doc + conventions card from conventions/",
"feat(pago-seeder): add provider credentials and test vehicles to MCP fixtures (#307)",
"docs(figma): resolve headless-vs-confirm in INTAKE (B/C headless, legacy attended) + status note (review fix)",
"feat(ios): App Store submission-prep skill (#306)",
"docs(figma): intake handoff contract — registry beside screen-inventory",
"docs(screen-canonicalizer): resolve §4 ref + registry output path + explicit no-direct-Figma (review fixes)",
"feat(screen-canonicalizer): cluster figma frames -> schema-valid registry (1.0.0)",
"feat(figma): canonical-screen-registry JSON schema + validated example",
"docs(figma-write): make /figma-screens bridge requirement a standalone precondition (review fix)",
"feat(figma-write): /figma-screens command + init scaffold workflow (1.2.0 -> 1.3.0)",
"feat(figma-write): layer-naming apply workflow, batched confirm (1.1.0 -> 1.2.0)",
"feat(figma-deep-dive): opt-in layer-audit mode, default frozen (1.4.0 -> 1.5.0)",
"feat(figma-conventions): add layers.md — layer naming taxonomy + ban-list (plugin 0.5.0 -> 0.5.1)",
"docs(figma-conventions): clarify naming conformance table + add base-form examples (review fixes)",
"feat(figma-conventions): naming root fix — screen != entry-point (plugin 0.4.0 -> 0.5.0)",
"docs(figma): implementation plan — screen identity + layer naming",
"docs(figma): spec — add project kickoff (Start moment)",
"docs(figma): spec — triggers + designer onboarding; lock component homes",
"docs(figma): spec — naming convention is the root fix",
"docs(figma): design — screen identity across flows + legible layer naming",
"chore(inspector-gadget): gitignore generated package-lock.json",
"feat(figma-deep-dive): package read+write bundle (plugin 0.3.0 -> 0.4.0)",
"feat(figma-write): surgical edits + screenshot validate loop (1.0.0 -> 1.1.0)",
"feat(figma-write): naming-apply skill with tiered inference + confirm gate",
"feat(figma-deep-dive): read-only naming audit (1.3.0 -> 1.4.0)",
"feat(figma-conventions): add naming convention + phase stubs",
"docs(figma-write): Phase 1 implementation plan",
"docs(figma-write): bundle into the figma-deep-dive plugin (one install)",
"docs(figma-write): reconcile spec to figma-deep-dive v1.3.0 (bridge-aware)",
"docs(figma-write): resolve distribution (symlink) + naming inference (tiered)",
"docs(figma-write): design spec for confirm-gated Figma write tooling",
"intake: graceful judge-CLI fallbacks (opus/sonnet) + fix #302 selftest fixture",
"Wire sdk-assets live/prod parity gate into android-release-train",
"Split sdk-assets parity gate: missing keys fail + auto-PR, value diffs warn",
"Address PR review: gate st10 witness on terminal-success",
"Fix intake-tools: st10 receipt witness + sync-pr executable bit",
"docs(figma-deep-dive): re-land bridge-aware README note + reconcile \"required\" box",
"feat(figma-deep-dive): bridge-aware extraction (bridge-first when viable, REST fallback)",
"fix(figma-deep-dive): tolerate payload-shape variance in jq extraction",
"fix(figma-deep-dive): exclude hidden layers (visible:false) from extraction",
"docs(android): add sdk assets live parity gate",
"feat(design-studio): optional ds-figma MCP bridge agent + context-driven color",
"feat(design-studio): ground the Hook Model from Hooked into the skill suite",
"feat(design-studio): add grounded product-design skill suite to marketplace",
"feat(shared/skills): integrate #293 + address #288 review on what-has-gone-wrong",
"create-prd: harden Phase 4 per 8-seat multi-model review board",
"create-prd: harden Phase 4 preflight per codex + kimi review",
"feat(shared/skills/what-has-gone-wrong): separate reported version from affected range in triage",
"create-prd: add optional Phase 4 to branch + open PR via /create-pr",
"Add /ios-create-branch as single source of truth for branch naming (#291)",
"Keep this PR gate-only: move intake changes to PR #289",
"intake: stamp intake_report_url into the pack + harden the report publisher",
"gate report: address codex/kimi/gemini review (security + robustness)",
"feat(shared/skills): add what-has-gone-wrong post-incident triage skill",
"gate + intake: cross-link the gate report to intake's status-page zhtml",
"gate-orchestrator: publish a zhtml run report to the Pago Report Hub",
"feat(pm-progress-report): tabbed layout, SVG rings, and report-track rendering rules",
"feat(pago-app-seeder): add gatekeeper-flags & notification-settings read tools (#286)",
"fix on the agent format",
"feat(pago-app-seeder): add static test-card and top-up fixtures (#284)",
"feat(pago-app-seeder): add eSIM reset for travel xsell re-arm (#280)",
"feat(mini-tester): inspect + auto-install pago-seeder MCP before testing (#281)",
"fix(pago-app-seeder): persist local base_override across CLI commands",
"feat(intake-orchestrator): fresh bead per run + per-stage push & live PR progress table",
"feat(commands): add android-ship autonomous ship-loop command"
];
